/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.messagemedia.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CheckRepliesResponse type.
 */
public class CheckRepliesResponse {
    private List<Object> replies;

    /**
     * Default constructor.
     */
    public CheckRepliesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  replies  List of Object value for replies.
     */
    public CheckRepliesResponse(
            List<Object> replies) {
        this.replies = replies;
    }

    /**
     * Getter for Replies.
     * @return Returns the List of Object
     */
    @JsonGetter("replies")
    public List<Object> getReplies() {
        return replies;
    }

    /**
     * Setter for Replies.
     * @param replies Value for List of Object
     */
    @JsonSetter("replies")
    public void setReplies(List<Object> replies) {
        this.replies = replies;
    }

    /**
     * Converts this CheckRepliesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CheckRepliesResponse [" + "replies=" + replies + "]";
    }

    /**
     * Builds a new {@link CheckRepliesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CheckRepliesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(replies);
        return builder;
    }

    /**
     * Class to build instances of {@link CheckRepliesResponse}.
     */
    public static class Builder {
        private List<Object> replies;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  replies  List of Object value for replies.
         */
        public Builder(List<Object> replies) {
            this.replies = replies;
        }

        /**
         * Setter for replies.
         * @param  replies  List of Object value for replies.
         * @return Builder
         */
        public Builder replies(List<Object> replies) {
            this.replies = replies;
            return this;
        }

        /**
         * Builds a new {@link CheckRepliesResponse} object using the set fields.
         * @return {@link CheckRepliesResponse}
         */
        public CheckRepliesResponse build() {
            return new CheckRepliesResponse(replies);
        }
    }
}
