/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.messagemedia.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CheckDeliveryReportsResponse type.
 */
public class CheckDeliveryReportsResponse {
    private List<Object> deliveryReports;

    /**
     * Default constructor.
     */
    public CheckDeliveryReportsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  deliveryReports  List of Object value for deliveryReports.
     */
    public CheckDeliveryReportsResponse(
            List<Object> deliveryReports) {
        this.deliveryReports = deliveryReports;
    }

    /**
     * Getter for DeliveryReports.
     * @return Returns the List of Object
     */
    @JsonGetter("delivery_reports")
    public List<Object> getDeliveryReports() {
        return deliveryReports;
    }

    /**
     * Setter for DeliveryReports.
     * @param deliveryReports Value for List of Object
     */
    @JsonSetter("delivery_reports")
    public void setDeliveryReports(List<Object> deliveryReports) {
        this.deliveryReports = deliveryReports;
    }

    /**
     * Converts this CheckDeliveryReportsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CheckDeliveryReportsResponse [" + "deliveryReports=" + deliveryReports + "]";
    }

    /**
     * Builds a new {@link CheckDeliveryReportsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CheckDeliveryReportsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deliveryReports);
        return builder;
    }

    /**
     * Class to build instances of {@link CheckDeliveryReportsResponse}.
     */
    public static class Builder {
        private List<Object> deliveryReports;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deliveryReports  List of Object value for deliveryReports.
         */
        public Builder(List<Object> deliveryReports) {
            this.deliveryReports = deliveryReports;
        }

        /**
         * Setter for deliveryReports.
         * @param  deliveryReports  List of Object value for deliveryReports.
         * @return Builder
         */
        public Builder deliveryReports(List<Object> deliveryReports) {
            this.deliveryReports = deliveryReports;
            return this;
        }

        /**
         * Builds a new {@link CheckDeliveryReportsResponse} object using the set fields.
         * @return {@link CheckDeliveryReportsResponse}
         */
        public CheckDeliveryReportsResponse build() {
            return new CheckDeliveryReportsResponse(deliveryReports);
        }
    }
}
