/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.messagemedia.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ConfirmDeliveryReportsAsReceivedRequest type.
 */
public class ConfirmDeliveryReportsAsReceivedRequest {
    private List<String> deliveryReportIds;

    /**
     * Default constructor.
     */
    public ConfirmDeliveryReportsAsReceivedRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deliveryReportIds  List of String value for deliveryReportIds.
     */
    public ConfirmDeliveryReportsAsReceivedRequest(
            List<String> deliveryReportIds) {
        this.deliveryReportIds = deliveryReportIds;
    }

    /**
     * Getter for DeliveryReportIds.
     * @return Returns the List of String
     */
    @JsonGetter("delivery_report_ids")
    public List<String> getDeliveryReportIds() {
        return deliveryReportIds;
    }

    /**
     * Setter for DeliveryReportIds.
     * @param deliveryReportIds Value for List of String
     */
    @JsonSetter("delivery_report_ids")
    public void setDeliveryReportIds(List<String> deliveryReportIds) {
        this.deliveryReportIds = deliveryReportIds;
    }

    /**
     * Converts this ConfirmDeliveryReportsAsReceivedRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConfirmDeliveryReportsAsReceivedRequest [" + "deliveryReportIds="
                + deliveryReportIds + "]";
    }

    /**
     * Builds a new {@link ConfirmDeliveryReportsAsReceivedRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConfirmDeliveryReportsAsReceivedRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deliveryReportIds);
        return builder;
    }

    /**
     * Class to build instances of {@link ConfirmDeliveryReportsAsReceivedRequest}.
     */
    public static class Builder {
        private List<String> deliveryReportIds;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deliveryReportIds  List of String value for deliveryReportIds.
         */
        public Builder(List<String> deliveryReportIds) {
            this.deliveryReportIds = deliveryReportIds;
        }

        /**
         * Setter for deliveryReportIds.
         * @param  deliveryReportIds  List of String value for deliveryReportIds.
         * @return Builder
         */
        public Builder deliveryReportIds(List<String> deliveryReportIds) {
            this.deliveryReportIds = deliveryReportIds;
            return this;
        }

        /**
         * Builds a new {@link ConfirmDeliveryReportsAsReceivedRequest} object using the set fields.
         * @return {@link ConfirmDeliveryReportsAsReceivedRequest}
         */
        public ConfirmDeliveryReportsAsReceivedRequest build() {
            return new ConfirmDeliveryReportsAsReceivedRequest(deliveryReportIds);
        }
    }
}
