/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.messagemedia.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * FormatEnum to be used.
 */
public enum FormatEnum {
    SMS,

    MMS,

    TTS;


    private static TreeMap<String, FormatEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        SMS.value = "SMS";
        MMS.value = "MMS";
        TTS.value = "TTS";

        valueMap.put("SMS", SMS);
        valueMap.put("MMS", MMS);
        valueMap.put("TTS", TTS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static FormatEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of FormatEnum values to list of string values.
     * @param toConvert The list of FormatEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<FormatEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (FormatEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 