/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.messagemedia.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SendMessagesResponse type.
 */
public class SendMessagesResponse {
    private List<Object> messages;

    /**
     * Default constructor.
     */
    public SendMessagesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  messages  List of Object value for messages.
     */
    public SendMessagesResponse(
            List<Object> messages) {
        this.messages = messages;
    }

    /**
     * Getter for Messages.
     * @return Returns the List of Object
     */
    @JsonGetter("messages")
    public List<Object> getMessages() {
        return messages;
    }

    /**
     * Setter for Messages.
     * @param messages Value for List of Object
     */
    @JsonSetter("messages")
    public void setMessages(List<Object> messages) {
        this.messages = messages;
    }

    /**
     * Converts this SendMessagesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SendMessagesResponse [" + "messages=" + messages + "]";
    }

    /**
     * Builds a new {@link SendMessagesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SendMessagesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messages);
        return builder;
    }

    /**
     * Class to build instances of {@link SendMessagesResponse}.
     */
    public static class Builder {
        private List<Object> messages;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messages  List of Object value for messages.
         */
        public Builder(List<Object> messages) {
            this.messages = messages;
        }

        /**
         * Setter for messages.
         * @param  messages  List of Object value for messages.
         * @return Builder
         */
        public Builder messages(List<Object> messages) {
            this.messages = messages;
            return this;
        }

        /**
         * Builds a new {@link SendMessagesResponse} object using the set fields.
         * @return {@link SendMessagesResponse}
         */
        public SendMessagesResponse build() {
            return new SendMessagesResponse(messages);
        }
    }
}
